substitutions:
  _SERVICE_NAME: driver-service

steps:
  # Step 1: Generate from Protobuf
  - name: bufbuild/buf@sha256:10c6aa179630e5cc53bc3ca46be87770ad8cc0bc2a30b39a0af3db8f33521976
    args:
      - generate

  # Step 2: Build Docker image using Bazel
  - name: gcr.io/cloud-builders/bazel@sha256:6d1fc137de84bb14a7cca6315c73089f54ce4667fc84a184d55cb08ba2bdfa1f
    args: [run, //cmd/api-server:container]

  # Step 3: Tag image
  - name: gcr.io/cloud-builders/docker@sha256:fd3be89e8d0e23bf0e91271dd2a17b49543028957129625bd743e7eb252bfaff
    args:
      - tag
      - api-server:latest
      - asia-south2-docker.pkg.dev/$PROJECT_ID/docker-registry/$_SERVICE_NAME:$COMMIT_SHA

  # Step 3: Tag image
  - name: gcr.io/cloud-builders/docker@sha256:fd3be89e8d0e23bf0e91271dd2a17b49543028957129625bd743e7eb252bfaff
    args:
      - tag
      - api-server:latest
      - asia-south2-docker.pkg.dev/$PROJECT_ID/docker-registry/$_SERVICE_NAME:$BRANCH_NAME

  # Step 3: Tag image
  - name: gcr.io/cloud-builders/docker@sha256:fd3be89e8d0e23bf0e91271dd2a17b49543028957129625bd743e7eb252bfaff
    args:
      - tag
      - api-server:latest
      - asia-south2-docker.pkg.dev/$PROJECT_ID/docker-registry/$_SERVICE_NAME:latest

  # Step 4: Push a Docker image
  - name: gcr.io/cloud-builders/docker@sha256:fd3be89e8d0e23bf0e91271dd2a17b49543028957129625bd743e7eb252bfaff
    args:
      - push
      - asia-south2-docker.pkg.dev/$PROJECT_ID/docker-registry/$_SERVICE_NAME:$COMMIT_SHA

  # Step 5: Push the new Cloud Run revision
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk@sha256:dd701e82bf5081fd7c8902ad371a9caf44b2122ae393f7c7f884f5c16b5ca0d2
    entrypoint: gcloud
    args:
      - run
      - deploy
      - $_SERVICE_NAME
      - --image
      - asia-south2-docker.pkg.dev/$PROJECT_ID/docker-registry/$_SERVICE_NAME:$COMMIT_SHA
      - --region=asia-south2
      - --allow-unauthenticated
      - --set-env-vars=PROJECT_ID=$PROJECT_ID,LOG_DEBUG=$_LOG_DEBUG,WALLET_SERVICE_HOST=$_WALLET_SERVICE_HOST
      - --max-instances=10
      - --port=50051
      - --use-http2

images:
  - asia-south2-docker.pkg.dev/$PROJECT_ID/docker-registry/$_SERVICE_NAME:$COMMIT_SHA
