substitutions:
  _SERVICE_NAME: driver-service

steps:
  # Step 1: Build Docker image
  - name: gcr.io/cloud-builders/docker@sha256:f1a9054315ba9ed114318e01ae26e0bfc50729f4ea72f535e6feeae68b8bbca2
    id: build
    args:
      - build
      - -t
      - api-server:latest
      - .
      - --cache-from
      - asia-south2-docker.pkg.dev/$PROJECT_ID/docker-registry/$_SERVICE_NAME:$BRANCH_NAME

  # Step 2: Tag image with COMMIT_SHA
  - name: gcr.io/cloud-builders/docker@sha256:f1a9054315ba9ed114318e01ae26e0bfc50729f4ea72f535e6feeae68b8bbca2
    id: tag-sha
    waitFor:
      - build
    args:
      - tag
      - api-server:latest
      - asia-south2-docker.pkg.dev/$PROJECT_ID/docker-registry/$_SERVICE_NAME:$COMMIT_SHA

  # Step 3: Tag image with BRANCH_NAME
  - name: gcr.io/cloud-builders/docker@sha256:f1a9054315ba9ed114318e01ae26e0bfc50729f4ea72f535e6feeae68b8bbca2
    id: tag-branch
    waitFor:
      - build
    args:
      - tag
      - api-server:latest
      - asia-south2-docker.pkg.dev/$PROJECT_ID/docker-registry/$_SERVICE_NAME:$BRANCH_NAME

  # Step 4: Tag image as latest
  - name: gcr.io/cloud-builders/docker@sha256:f1a9054315ba9ed114318e01ae26e0bfc50729f4ea72f535e6feeae68b8bbca2
    id: tag-latest
    waitFor:
      - build
    args:
      - tag
      - api-server:latest
      - asia-south2-docker.pkg.dev/$PROJECT_ID/docker-registry/$_SERVICE_NAME:latest

  # Step 5: Push Docker image
  - name: gcr.io/cloud-builders/docker@sha256:f1a9054315ba9ed114318e01ae26e0bfc50729f4ea72f535e6feeae68b8bbca2
    id: push
    waitFor:
      - tag-sha
    args:
      - push
      - asia-south2-docker.pkg.dev/$PROJECT_ID/docker-registry/$_SERVICE_NAME:$COMMIT_SHA

  # Step 6: Deploy to Cloud Run
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk@sha256:d20e89ac0b9b23e5c2839d880145c5ca57b0f23fbb5fc24e740e898785ea3871
    id: deploy
    waitFor:
      - push
    entrypoint: gcloud
    args:
      - run
      - deploy
      - $_SERVICE_NAME
      - --image
      - asia-south2-docker.pkg.dev/$PROJECT_ID/docker-registry/$_SERVICE_NAME:$COMMIT_SHA
      - --region=asia-south2
      - --allow-unauthenticated
      - --set-env-vars=PROJECT_ID=$PROJECT_ID,LOG_DEBUG=$_LOG_DEBUG,WALLET_SERVICE_HOST=$_WALLET_SERVICE_HOST
      - --max-instances=10
      - --port=50051
      - --use-http2

images:
  - asia-south2-docker.pkg.dev/$PROJECT_ID/docker-registry/$_SERVICE_NAME:$COMMIT_SHA
  - asia-south2-docker.pkg.dev/$PROJECT_ID/docker-registry/$_SERVICE_NAME:$BRANCH_NAME
  - asia-south2-docker.pkg.dev/$PROJECT_ID/docker-registry/$_SERVICE_NAME:latest
