substitutions:
  _SERVICE_NAME: driver-service

steps:
  # Step 1: Build Docker image
  - name: gcr.io/cloud-builders/docker@sha256:6982f007d1130a9db2044ba5d09b0005a3f3e9848b983590aa99d8072a5a2bfc
    id: build
    args:
      - build
      - -t
      - api-server:latest
      - .
      - --cache-from
      - asia-south2-docker.pkg.dev/$PROJECT_ID/docker-registry/$_SERVICE_NAME:$BRANCH_NAME

  # Step 2: Tag image with COMMIT_SHA
  - name: gcr.io/cloud-builders/docker@sha256:6982f007d1130a9db2044ba5d09b0005a3f3e9848b983590aa99d8072a5a2bfc
    id: tag-sha
    waitFor:
      - build
    args:
      - tag
      - api-server:latest
      - asia-south2-docker.pkg.dev/$PROJECT_ID/docker-registry/$_SERVICE_NAME:$COMMIT_SHA

  # Step 3: Tag image with BRANCH_NAME
  - name: gcr.io/cloud-builders/docker@sha256:6982f007d1130a9db2044ba5d09b0005a3f3e9848b983590aa99d8072a5a2bfc
    id: tag-branch
    waitFor:
      - build
    args:
      - tag
      - api-server:latest
      - asia-south2-docker.pkg.dev/$PROJECT_ID/docker-registry/$_SERVICE_NAME:$BRANCH_NAME

  # Step 4: Tag image as latest
  - name: gcr.io/cloud-builders/docker@sha256:6982f007d1130a9db2044ba5d09b0005a3f3e9848b983590aa99d8072a5a2bfc
    id: tag-latest
    waitFor:
      - build
    args:
      - tag
      - api-server:latest
      - asia-south2-docker.pkg.dev/$PROJECT_ID/docker-registry/$_SERVICE_NAME:latest

  # Step 5: Push Docker image
  - name: gcr.io/cloud-builders/docker@sha256:6982f007d1130a9db2044ba5d09b0005a3f3e9848b983590aa99d8072a5a2bfc
    id: push
    waitFor:
      - tag-sha
    args:
      - push
      - asia-south2-docker.pkg.dev/$PROJECT_ID/docker-registry/$_SERVICE_NAME:$COMMIT_SHA

  # Step 6: Deploy to Cloud Run
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk@sha256:d8235e1878315aaad842e56dcb4f269c16540dba99a5692342f91f0f50c40d15
    id: deploy
    waitFor:
      - push
    entrypoint: gcloud
    args:
      - run
      - deploy
      - $_SERVICE_NAME
      - --image
      - asia-south2-docker.pkg.dev/$PROJECT_ID/docker-registry/$_SERVICE_NAME:$COMMIT_SHA
      - --region=asia-south2
      - --allow-unauthenticated
      - --set-env-vars=PROJECT_ID=$PROJECT_ID,LOG_DEBUG=$_LOG_DEBUG,WALLET_SERVICE_HOST=$_WALLET_SERVICE_HOST
      - --max-instances=10
      - --port=50051
      - --use-http2

images:
  - asia-south2-docker.pkg.dev/$PROJECT_ID/docker-registry/$_SERVICE_NAME:$COMMIT_SHA
  - asia-south2-docker.pkg.dev/$PROJECT_ID/docker-registry/$_SERVICE_NAME:$BRANCH_NAME
  - asia-south2-docker.pkg.dev/$PROJECT_ID/docker-registry/$_SERVICE_NAME:latest
