substitutions:
  _SERVICE_NAME: driver-service

steps:
  # Step 1: Generate from Protobuf
  - name: bufbuild/buf@sha256:e59a3f1722f4dafabdb6c7129795a269b087acaddadb08bc7866a0a86c9d0451
    args:
      - generate

  # Step 2: Build Docker image using Bazel
  - name: gcr.io/cloud-builders/bazel@sha256:79d9fa65f2d6f47a0984e97c9140a497c15441378fc1cce88f35cb2e33dd3078
    args: [run, //cmd/api-server:container]

  # Step 3: Tag image
  - name: gcr.io/cloud-builders/docker@sha256:83dc86fe2c6a6803d8f7488c96b04ae9075131ea11289d35912a45a06ca888b8
    args:
      - tag
      - api-server:latest
      - asia-south2-docker.pkg.dev/$PROJECT_ID/docker-registry/$_SERVICE_NAME:$COMMIT_SHA

  # Step 3: Tag image
  - name: gcr.io/cloud-builders/docker@sha256:83dc86fe2c6a6803d8f7488c96b04ae9075131ea11289d35912a45a06ca888b8
    args:
      - tag
      - api-server:latest
      - asia-south2-docker.pkg.dev/$PROJECT_ID/docker-registry/$_SERVICE_NAME:$BRANCH_NAME

  # Step 3: Tag image
  - name: gcr.io/cloud-builders/docker@sha256:83dc86fe2c6a6803d8f7488c96b04ae9075131ea11289d35912a45a06ca888b8
    args:
      - tag
      - api-server:latest
      - asia-south2-docker.pkg.dev/$PROJECT_ID/docker-registry/$_SERVICE_NAME:latest

  # Step 4: Push a Docker image
  - name: gcr.io/cloud-builders/docker@sha256:83dc86fe2c6a6803d8f7488c96b04ae9075131ea11289d35912a45a06ca888b8
    args:
      - push
      - asia-south2-docker.pkg.dev/$PROJECT_ID/docker-registry/$_SERVICE_NAME:$COMMIT_SHA

  # Step 5: Push the new Cloud Run revision
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk@sha256:b6b27865362c69301e18c8f5d00a66aa06b984218a2d43bd7c57eea8e661b9c9
    entrypoint: gcloud
    args:
      - run
      - deploy
      - $_SERVICE_NAME
      - --image
      - asia-south2-docker.pkg.dev/$PROJECT_ID/docker-registry/$_SERVICE_NAME:$COMMIT_SHA
      - --region=asia-south2
      - --allow-unauthenticated
      - --set-env-vars=PROJECT_ID=$PROJECT_ID,LOG_DEBUG=$_LOG_DEBUG,WALLET_SERVICE_HOST=$_WALLET_SERVICE_HOST
      - --max-instances=10
      - --port=50051
      - --use-http2

images:
  - asia-south2-docker.pkg.dev/$PROJECT_ID/docker-registry/$_SERVICE_NAME:$COMMIT_SHA
