substitutions:
  _SERVICE_NAME: driver-service

steps:
  # Step 1: Generate from Protobuf
  - name: bufbuild/buf@sha256:f5b08d09cd61a90ab21563cc9bdf3b197cb7e9feaf4793e6478a92a7b270c93c
    args:
      - generate

  # Step 2: Build Docker image using Bazel
  - name: gcr.io/cloud-builders/bazel@sha256:f8c96ebd14aa6fa03f52b0c65ebe147fc2de9cb0f736e8953f0877b1aaf4e333
    args: [run, //cmd/api-server:container]

  # Step 3: Tag image
  - name: gcr.io/cloud-builders/docker@sha256:41e017d3f3bf1629f90e389b4dd1d5cbb3bae9fcfc33c44464d618154301c905
    args:
      - tag
      - api-server:latest
      - asia-south2-docker.pkg.dev/$PROJECT_ID/docker-registry/$_SERVICE_NAME:$COMMIT_SHA

  # Step 3: Tag image
  - name: gcr.io/cloud-builders/docker@sha256:41e017d3f3bf1629f90e389b4dd1d5cbb3bae9fcfc33c44464d618154301c905
    args:
      - tag
      - api-server:latest
      - asia-south2-docker.pkg.dev/$PROJECT_ID/docker-registry/$_SERVICE_NAME:$BRANCH_NAME

  # Step 3: Tag image
  - name: gcr.io/cloud-builders/docker@sha256:41e017d3f3bf1629f90e389b4dd1d5cbb3bae9fcfc33c44464d618154301c905
    args:
      - tag
      - api-server:latest
      - asia-south2-docker.pkg.dev/$PROJECT_ID/docker-registry/$_SERVICE_NAME:latest

  # Step 4: Push a Docker image
  - name: gcr.io/cloud-builders/docker@sha256:41e017d3f3bf1629f90e389b4dd1d5cbb3bae9fcfc33c44464d618154301c905
    args:
      - push
      - asia-south2-docker.pkg.dev/$PROJECT_ID/docker-registry/$_SERVICE_NAME:$COMMIT_SHA

  # Step 5: Push the new Cloud Run revision
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk@sha256:a6b07af7cfcb8e6ba0162abb4093418404f1ccaa485a5ea3481258af50d67e38
    entrypoint: gcloud
    args:
      - run
      - deploy
      - $_SERVICE_NAME
      - --image
      - asia-south2-docker.pkg.dev/$PROJECT_ID/docker-registry/$_SERVICE_NAME:$COMMIT_SHA
      - --region=asia-south2
      - --allow-unauthenticated
      - --set-env-vars=PROJECT_ID=$PROJECT_ID,LOG_DEBUG=$_LOG_DEBUG,WALLET_SERVICE_HOST=$_WALLET_SERVICE_HOST
      - --max-instances=10
      - --port=50051
      - --use-http2

images:
  - asia-south2-docker.pkg.dev/$PROJECT_ID/docker-registry/$_SERVICE_NAME:$COMMIT_SHA
