substitutions:
  _SERVICE_NAME: driver-service

steps:
  # Step 1: Generate from Protobuf
  - name: bufbuild/buf@sha256:f5b08d09cd61a90ab21563cc9bdf3b197cb7e9feaf4793e6478a92a7b270c93c
    args:
      - generate

  # Step 2: Build Docker image using Bazel
  - name: gcr.io/cloud-builders/bazel@sha256:eaf2efa0c487bc693023515b4bb43fd773498a725f8ec820927b3626a70efce7
    args: [run, //cmd/api-server:container]

  # Step 3: Tag image
  - name: gcr.io/cloud-builders/docker@sha256:99be791d1369ba08229ff5d6b633b62917b729e2e360e5a1b39fe625951cc3ca
    args:
      - tag
      - api-server:latest
      - asia-south2-docker.pkg.dev/$PROJECT_ID/docker-registry/$_SERVICE_NAME:$COMMIT_SHA

  # Step 3: Tag image
  - name: gcr.io/cloud-builders/docker@sha256:99be791d1369ba08229ff5d6b633b62917b729e2e360e5a1b39fe625951cc3ca
    args:
      - tag
      - api-server:latest
      - asia-south2-docker.pkg.dev/$PROJECT_ID/docker-registry/$_SERVICE_NAME:$BRANCH_NAME

  # Step 3: Tag image
  - name: gcr.io/cloud-builders/docker@sha256:99be791d1369ba08229ff5d6b633b62917b729e2e360e5a1b39fe625951cc3ca
    args:
      - tag
      - api-server:latest
      - asia-south2-docker.pkg.dev/$PROJECT_ID/docker-registry/$_SERVICE_NAME:latest

  # Step 4: Push a Docker image
  - name: gcr.io/cloud-builders/docker@sha256:99be791d1369ba08229ff5d6b633b62917b729e2e360e5a1b39fe625951cc3ca
    args:
      - push
      - asia-south2-docker.pkg.dev/$PROJECT_ID/docker-registry/$_SERVICE_NAME:$COMMIT_SHA

  # Step 5: Push the new Cloud Run revision
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk@sha256:f5608252f6af4b26d6b494d58648201d3f083761b5dd187a0242820de741c238
    entrypoint: gcloud
    args:
      - run
      - deploy
      - $_SERVICE_NAME
      - --image
      - asia-south2-docker.pkg.dev/$PROJECT_ID/docker-registry/$_SERVICE_NAME:$COMMIT_SHA
      - --region=asia-south2
      - --allow-unauthenticated
      - --set-env-vars=PROJECT_ID=$PROJECT_ID,LOG_DEBUG=$_LOG_DEBUG,WALLET_SERVICE_HOST=$_WALLET_SERVICE_HOST
      - --max-instances=10
      - --port=50051
      - --use-http2

images:
  - asia-south2-docker.pkg.dev/$PROJECT_ID/docker-registry/$_SERVICE_NAME:$COMMIT_SHA
