name: Trunk Check setup
description: Set up dependencies for Trunk Check

runs:
  using: composite
  steps:
    - uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe # v4
      with:
        go-version-file: go.mod

    - name: Setup Buf
      uses: bufbuild/buf-setup-action@6bdfab1cc71322c663d891914e69da7a6c2c5f52 # v1.27.1
      with:
        buf_user: ${{ env.BUF_USER }}
        buf_api_token: ${{ env.BUF_TOKEN }}
        github_token: ${{ github.token }}

    - name: Build protobuf
      uses: trunk-io/breakpoint@d13a81dd8da4563f4696b2a860645107ad971aa0 # v1
      with:
        breakpoint-id: buf-generate
        run: buf generate
        trunk-token: ${{ env.TRUNK_TOKEN }}
        org: ride
