name: Trunk Check setup
description: Set up dependencies for Trunk Check

runs:
  using: composite
  steps:
    - uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe # v4
      with:
        go-version-file: go.mod

    - name: Setup Buf
      uses: bufbuild/buf-setup-action@1158f4fa81bc02e1ff62abcca6d516c9e24c77da # v1.27.2
      with:
        buf_user: ${{ env.BUF_USER }}
        buf_api_token: ${{ env.BUF_TOKEN }}
        github_token: ${{ github.token }}

    - name: Build protobuf
      uses: trunk-io/breakpoint@f8a1f08369323ed46f3ef7161d3d0a2fdc3488df # v1
      with:
        breakpoint-id: buf-generate
        run: buf generate
        trunk-token: ${{ env.TRUNK_TOKEN }}
        org: ride
