name: Trunk Check setup
description: Set up dependencies for Trunk Check

runs:
  using: composite
  steps:
    - uses: actions/setup-go@v4
      with:
        go-version-file: go.mod

    - name: Setup Buf
      uses: bufbuild/buf-setup-action@v1.26.1
      with:
        buf_user: ${{ env.BUF_USER }}
        buf_api_token: ${{ secrets.BUF_TOKEN }}
        github_token: ${{ github.token }}

    - name: Build protobuf
      uses: trunk-io/breakpoint@v1
      with:
        breakpoint-id: buf-generate
        run: buf generate
        trunk-token: ${{ secrets.TRUNK_TOKEN }}
        org: ride
