name: Trunk Check setup
description: Set up dependencies for Trunk Check

runs:
  using: composite
  steps:
    - name: Setup Buf
      uses: bufbuild/buf-setup-action@88db93f5d74ffa329bb43e42aa95cd822697d214 # v1.29.0
      with:
        buf_user: ${{ env.BUF_USER }}
        buf_api_token: ${{ env.BUF_TOKEN }}
        github_token: ${{ github.token }}

    - name: Build protobuf
      uses: trunk-io/breakpoint@f8a1f08369323ed46f3ef7161d3d0a2fdc3488df # v1
      with:
        breakpoint-id: buf-generate
        run: buf generate
        trunk-token: ${{ env.TRUNK_TOKEN }}
        org: ride
