// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/ride-app/driver-service/logger"
	"github.com/ride-app/driver-service/repositories/driver"
	"github.com/ride-app/driver-service/repositories/vehicle"
	"github.com/ride-app/driver-service/repositories/wallet"
	"github.com/ride-app/driver-service/service"
	"github.com/ride-app/driver-service/third-party"
)

// Injectors from wire.go:

func InitializeService() (*service.DriverServiceServer, error) {
	zapLogger := logger.New()
	app, err := thirdparty.NewFirebaseApp(zapLogger)
	if err != nil {
		return nil, err
	}
	firebaseImpl, err := driverrepository.NewFirebaseDriverRepository(app, zapLogger)
	if err != nil {
		return nil, err
	}
	vehiclerepositoryFirebaseImpl, err := vehiclerepository.NewFirebaseVehicleRepository(app, zapLogger)
	if err != nil {
		return nil, err
	}
	impl, err := walletrepository.New(zapLogger)
	if err != nil {
		return nil, err
	}
	driverServiceServer := service.New(firebaseImpl, vehiclerepositoryFirebaseImpl, impl, zapLogger)
	return driverServiceServer, nil
}
