name: Auto Merge Bots

on:
  pull_request_target:
    types:
      - opened
      - synchronize
      - reopened

permissions:
  contents: read
  pull-requests: write

jobs:
  comment_pr_if_bot:
    name: Comment on pull request if bot
    uses: deb-tech-n-sol/workflows/.github/workflows/auto-merge.yaml@main
