name: Auto Merge Bots
on:
  pull_request_target:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  comment_pr_if_bot:
    name: Comment on pull request if bot
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.user.type == 'Bot' }}
    steps:
      - uses: actions/labeler@ac9175f8a1f3625fd0d4fb234536d26811351594 # v4
        with:
          repo-token: ${{ github.token }}
          sync-labels: true

      - uses: thollander/actions-comment-pull-request@1d3973dc4b8e1399c0620d3f2b1aa5e795465308 # v2
        with:
          message: |
            /trunk merge
