name: Buf push
permissions: read-all

on:
  push:
    paths:
      - api/**
    branches:
      - main

jobs:
  buf-push:
    uses: dragonfish-tech/workflows/.github/workflows/buf-push.yaml@main
    with:
      buf-mod-dir: api
    secrets: inherit
