name: Merge

permissions: read-all

on:
  push:
    branches:
      - trunk-merge/**

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    name: Build
    steps:
      - name: Checkout Code
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

      - name: Cache Bazel
        uses: actions/cache@704facf57e6136b1bc63b828d79edcd491f0ee84 # v3
        with:
          path: |
            ~/.cache/bazel
          key: ${{ runner.os }}-bazel-${{ hashFiles('.bazelversion', '.bazelrc', 'WORKSPACE', 'WORKSPACE.bazel', 'MODULE.bazel') }}
          restore-keys: |
            ${{ runner.os }}-bazel-

      - uses: bufbuild/buf-setup-action@382440cdb8ec7bc25a68d7b4711163d95f7cc3aa # v1.28.1
        with:
          buf_user: ${{ env.BUF_USER }}
          buf_api_token: ${{ secrets.BUF_TOKEN }}
          github_token: ${{ github.token }}

      - name: Build protobuf
        run: buf generate

      - name: Build
        run: bazelisk build //... --enable_bzlmod
        # env:
        #   USE_BAZEL_VERSION: 6.4.0
