name: Merge

permissions: read-all

on:
  push:
    branches:
      - trunk-merge/**

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    name: Build
    env:
      TEST_TAG: ride/driver-service
    steps:
      - name: Checkout Code
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@4fd812986e6c8c2a69e18311145f9371337f27d4 # v3

      - name: Build and export cache
        uses: docker/build-push-action@1ca370b3a9802c92e886402e0dd88098a2533b12 # v6
        with:
          load: true
          tags: ${{ env.TEST_TAG }}
          context: .
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # - name: Test
      #   run: |
      #     docker run --rm ${{ env.TEST_TAG }}
