name: PR

permissions: read-all

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    name: Build
    env:
      TEST_TAG: ride/driver-service/pr:${{ github.event.number }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and export to Docker
        uses: docker/build-push-action@v6
        with:
          load: true
          tags: ${{ env.TEST_TAG }}
          context: .
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # - name: Test
      #   run: |
      #     docker run --rm ${{ env.TEST_TAG }}

  auto_merge:
    permissions:
      contents: read
      pull-requests: write
    name: Auto Merge PR if bot
    uses: dragonfish/workflows/.github/workflows/auto-merge.yaml@main
