name: pr
permissions: read-all

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - trunk-merge/**

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Build+Unit Tests
    steps:
      - name: Checkout Code
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

      - name: Mount bazel cache
        uses: actions/cache@704facf57e6136b1bc63b828d79edcd491f0ee84 # v3
        with:
          path: /home/runner/.cache/bazel
          key: bazel

      - uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe # v4
        with:
          go-version-file: go.mod

      - uses: bufbuild/buf-setup-action@6bdfab1cc71322c663d891914e69da7a6c2c5f52 # v1.27.1
        with:
          buf_user: ${{ env.BUF_USER }}
          buf_api_token: ${{ secrets.BUF_TOKEN }}
          github_token: ${{ github.token }}

      - name: Build protobuf
        uses: trunk-io/breakpoint@d13a81dd8da4563f4696b2a860645107ad971aa0 # v1
        with:
          breakpoint-id: buf-generate
          run: buf generate
          trunk-token: ${{ secrets.TRUNK_TOKEN }}
          org: ride

      - name: Build
        run: bazel build //...

      # - name: Lint
      #   uses: trunk-io/trunk-action@v1

      # - name: Unit Tests
      #   run: go run github.com/onsi/ginkgo/v2/ginkgo -r --randomize-all --randomize-suites --fail-on-pending --keep-going --cover --coverprofile=cover.json --race --trace --json-report=report.json --timeout=10m -ldflags "-X google.golang.org/protobuf/reflect/protoregistry.conflictPolicy=warn" -tags=unit_tests

      # - name: Upload coverage to Codecov
      #   uses: codecov/codecov-action@v3
      #   with:
      #     token: ${{ secrets.CODECOV_TOKEN }}
      #     flags: unit-tests
      #     files: ./cover.json,./report.json
      #     fail_ci_if_error: true
      #     verbose: true
