name: pr
permissions: read-all

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - trunk-merge/**

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Build+Unit Tests
    steps:
      - name: Checkout Code
        uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4

      - uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe # v4
        with:
          go-version-file: go.mod

      - uses: bufbuild/buf-setup-action@93435dfe1238e4a6ee49f795b394aeb1e5afc1f8 # v1.27.0
        with:
          buf_user: ${{ env.BUF_USER }}
          buf_api_token: ${{ secrets.BUF_TOKEN }}
          github_token: ${{ github.token }}

      - name: Build protobuf
        uses: trunk-io/breakpoint@960d99758d917c9a6021685f775e648e00f43f9a # v1
        with:
          breakpoint-id: buf-generate
          run: buf generate
          trunk-token: ${{ secrets.TRUNK_TOKEN }}
          org: ride

      - name: Build
        run: bazel build //...

      # - name: Lint
      #   uses: trunk-io/trunk-action@v1

      # - name: Unit Tests
      #   run: go run github.com/onsi/ginkgo/v2/ginkgo -r --randomize-all --randomize-suites --fail-on-pending --keep-going --cover --coverprofile=cover.json --race --trace --json-report=report.json --timeout=10m -ldflags "-X google.golang.org/protobuf/reflect/protoregistry.conflictPolicy=warn" -tags=unit_tests

      # - name: Upload coverage to Codecov
      #   uses: codecov/codecov-action@v3
      #   with:
      #     token: ${{ secrets.CODECOV_TOKEN }}
      #     flags: unit-tests
      #     files: ./cover.json,./report.json
      #     fail_ci_if_error: true
      #     verbose: true
