name: Read All

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pull-requests: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Print debug information
        run: |
          echo "Current directory:"
          pwd
          echo "Contents of buf configuration files:"
          cat buf.yaml
          cat buf.gen.yaml
          echo "Environment variables:"
          env

      - name: Build and test
        run: |
          buf version
          buf generate --verbose
          # Add additional build and test commands here
