name: Read All

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pull-requests: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and test
        run: |
          buf generate --path ${{ github.workspace }}
          # Add additional build and test commands here
